// Generated by CoffeeScript 1.9.2
(function() {
  window.Unrem = function(init_val) {
    return {
      iterator: 0,
      stack: [Imuta.clone(init_val)],
      purge: function() {
        this.iterator = 0;
        this.stack = this.stack.slice(0, 1);
        return this.stack[this.iterator];
      },
      push: function(value) {
        if (!(Imuta.equal(this.stack[this.iterator], value))) {
          if ((this.iterator + 1) !== this.stack.length) {
            this.stack = this.stack.slice(0, this.iterator + 1);
          }
          this.iterator++;
          this.stack.push(Imuta.clone(value));
        }
        return value;
      },
      undo: function() {
        if (this.iterator !== 0) {
          this.iterator--;
        }
        return this.stack[this.iterator];
      },
      redo: function() {
        if ((this.iterator + 1) !== this.stack.length) {
          this.iterator++;
        }
        return this.stack[this.iterator];
      },
      get: function() {
        return this.stack[this.iterator];
      }
    };
  };

}).call(this);
