// Generated by CoffeeScript 1.9.2
(function() {
  window.Unrem = function(init_val) {
    return {
      stack_main: [Imuta.clone(init_val)],
      stack_second: [],
      purge: function() {
        this.stack_second = [];
        this.stack_main = [this.stack_main[0]];
        return this.get();
      },
      push: function(value) {
        if (!(Imuta.equal(this.get(), value))) {
          if (Imuta.equal(this.stack_second[this.stack_second.length - 1], value) && (this.stack_second.length !== 0)) {
            this.redo();
          } else {
            this.stack_second = [];
            this.stack_main.push(Imuta.clone(value));
          }
        }
        return value;
      },
      undo: function() {
        if (this.stack_main.length !== 1) {
          this.stack_second.push(this.stack_main.pop());
        }
        return this.get();
      },
      redo: function() {
        if (this.stack_second.length !== 0) {
          this.stack_main.push(this.stack_second.pop());
        }
        return this.get();
      },
      get: function() {
        return this.stack_main[this.stack_main.length - 1];
      }
    };
  };

}).call(this);
